name: CI

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: install, build, test
        run: |
          pnpm i
          pnpm build
          pnpm test
        env:
          CI: true
